# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'Guardfile'
    - 'bin/**'
    - 'tmp/**/*'
Metrics/BlockLength:
  Enabled: false
MethodLength:
  Max: 20
Style/FileName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
LineLength:
  Enabled: false
