Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
